config/routes.rb
Rails.application.routes.draw do

  resources :asignaciones
  resources :proveedores
  resources :personas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/login', to:'seguridad#login'
  get '/inicio', to:'inicio#casa'
  get '/noacceso', to:'inicio#noacceso'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignacione.rb
class Asignacione < ApplicationRecord
  belongs_to :persona
end

app/models/equipo.rb
# == Schema Information
#
# Table name: equipos
#
#  id             :integer          not null, primary key
#  Placa          :string
#  Modelo         :string
#  Serie          :string
#  IdEstadoEquipo :string
#  IdTipoEquipo   :string
#  IdArea         :string
#  eliminado      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Equipo < ApplicationRecord
	has_many :vencimientos
end

app/models/opcione.rb
# == Schema Information
#
# Table name: opciones
#
#  id           :integer          not null, primary key
#  idpadre      :integer
#  opcion       :string
#  url          :string
#  estadoopcion :string
#  orden        :string
#  eshoja       :boolean
#  controller   :string
#  eliminado    :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Opcione < ApplicationRecord
	has_many :rol_opcion_operacione
end

app/models/parametro.rb
# == Schema Information
#
# Table name: parametros
#
#  id              :integer          not null, primary key
#  atributo        :string
#  descripcion     :string
#  estadoParametro :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Parametro < ApplicationRecord
	has_many :valor_parametro
	
end

app/models/persona.rb
class Persona < ApplicationRecord
	has_many :asignaciones
end

app/models/proveedore.rb
class Proveedore < ApplicationRecord
end

app/models/usuario.rb
# == Schema Information
#
# Table name: usuarios
#
#  id              :integer          not null, primary key
#  usuario         :string
#  idrol           :integer
#  idestadousuario :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  eliminado       :integer          default(0)
#  password        :string
#

include Servicios
class Usuario < ApplicationRecord  
	 before_save :encriptarPass
	
   has_many :rol_opcion_operacione
      
  validates :usuario, presence: true, length: { minimum: 4 },
    uniqueness: { case_sensitive: false,message: "Usuario existe. Verifique" }
  validates :password, presence: {message: "Debe agregar un password valido." }

  scope :sin_eliminados, -> { where(eliminado: 0)   }

  private 
  def encriptarPass 
    if self.password !=nil           	
    	self.password = Encriptar(self.password)
    end    
 end

end

app/models/valor_parametro.rb
# == Schema Information
#
# Table name: valor_parametros
#
#  id                   :integer          not null, primary key
#  parametroId          :integer
#  valor                :string
#  orden                :string(3)
#  estadoValorParametro :string(1)
#  eliminado            :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  parametro_id         :integer
#

class ValorParametro < ApplicationRecord
	 belongs_to :parametro
end

app/models/vencimiento.rb
# == Schema Information
#
# Table name: vencimientos
#
#  id                  :integer          not null, primary key
#  Equipo_id           :integer
#  FechaInicion        :date
#  FechaFinal          :date
#  Comentario          :string
#  IdTipoVencimineto   :string
#  IdEstadoVencimiento :string
#  Referencia          :string
#  eliminado           :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Vencimiento < ApplicationRecord
  belongs_to :Equipo
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :auth!
  require "pp"
  include Servicios
  private
     #implementando Autenticación

    def auth!
        
       if session[:idrol]== ""     
           puts "No hay session"
           redirect_to "/login"
           return  
                     
       end
   
     # implementando  autorizacion
       
        puts "Hay Session"
    
       #verb=request.env["REQUEST_METHOD"]
       # accion=action_name      
      uri= request.original_url  
     
      idrol= session[:idrol]       
      
      uridiv = uri.split('/') 
      if uridiv.length() > 3  and idrol !=""
        controlador = uridiv[3].split("?").first.to_s  
           
        acceso=validarAccesoOpcion(idrol,controlador)
         
        if !acceso 
           redirect_to "/noacceso"
           return
        end
          
          # obteniendo las oepraciones para la accion o controlador 
          if controlador !="inicio"
              @operaciones=getOperaciones(idrol,controlador) 
               puts "operaciones=#{@operaciones}"    
        end
      end 
    end
end

app/controllers/proveedores_controller.rb
class ProveedoresController < BaseController
  before_action :set_proveedore, only: [:show, :edit, :update, :destroy]

  # GET /proveedores
  # GET /proveedores.json
  def index
    @proveedores = Proveedore.all
  end

  # GET /proveedores/1
  # GET /proveedores/1.json
  def show
  end

  # GET /proveedores/new
  def new
    @proveedore = Proveedore.new
  end

  # GET /proveedores/1/edit
  def edit
  end

  # POST /proveedores
  # POST /proveedores.json
  def create
    @proveedore = Proveedore.new(proveedore_params)

    respond_to do |format|
      if @proveedore.save
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully created.' }
        format.json { render :show, status: :created, location: @proveedore }
      else
        format.html { render :new }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedores/1
  # PATCH/PUT /proveedores/1.json
  def update
    respond_to do |format|
      if @proveedore.update(proveedore_params)
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully updated.' }
        format.json { render :show, status: :ok, location: @proveedore }
      else
        format.html { render :edit }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedores/1
  # DELETE /proveedores/1.json
  def destroy
    @proveedore.destroy
    respond_to do |format|
      format.html { redirect_to proveedores_url, notice: 'Proveedore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedore
      @proveedore = Proveedore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proveedore_params
      params.require(:proveedore).permit(:identificacion, :nombre, :idCiudad, :idDpto, :dirreccion, :correo, :telefonos, :idTipoProv, :idEstadoProv, :idCategoriaProv, :comentario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/opciones_helper.rb
module OpcionesHelper
end

app/helpers/parametros_helper.rb
module ParametrosHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/helpers/seguridad_helper.rb
module SeguridadHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/proveedores/_form.html.erb
<%= form_with(model: proveedore, local: true) do |form| %>
  <% if proveedore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proveedore.errors.count, "error") %> prohibited this proveedore from being saved:</h2>

      <ul>
      <% proveedore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row col-sm-4">
    <%= form.label :identificacion %>
    <%= form.number_field :identificacion, id: :proveedore_identificacion, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :proveedore_nombre, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idCiudad %>
    <%= form.number_field :idCiudad, id: :proveedore_idCiudad, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idDpto %>
    <%= form.number_field :idDpto, id: :proveedore_idDpto, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :dirreccion %>
    <%= form.text_field :dirreccion, id: :proveedore_dirreccion, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :proveedore_correo, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :telefonos %>
    <%= form.number_field :telefonos, id: :proveedore_telefonos, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idTipoProv %>
    <%= form.number_field :idTipoProv, id: :proveedore_idTipoProv, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idEstadoProv %>
    <%= form.number_field :idEstadoProv, id: :proveedore_idEstadoProv, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idCategoriaProv %>
    <%= form.number_field :idCategoriaProv, id: :proveedore_idCategoriaProv, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :comentario %>
    <%= form.text_field :comentario, id: :proveedore_comentario, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", :class=> "btn btn-secondary" %>
    <%= link_to 'Eliminar', proveedore, :class => "btn btn-danger", method: :delete, data: { confirm: 'Confirme Eliminación?' } %>
  </div>
<% end %>

app/views/proveedores/edit.html.erb
<h1>Editing Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Show', @proveedore %> |
<%= link_to 'Back', proveedores_path %>

app/views/proveedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores</h1>

<%= link_to 'Nuevo', new_proveedore_path, :class=>"btn btn-primary btn-sm" %>

<table class="table table-bordered table-sm">
  <thead>
    <tr>
      <th class="w-50 text-center">Identificacion</th>
      <th class="w-50 text-center">Nombre</th>
      <th class="w-50 text-center">Idciudad</th>
      <th class="w-50 text-center">Iddpto</th>
      <th class="w-50 text-center">Dirreccion</th>
      <th class="w-50 text-center">Correo</th>
      <th class="w-50 text-center">Telefonos</th>
      <th class="w-50 text-center">Idtipoprov</th>
      <th class="w-50 text-center">Idestadoprov</th>
      <th class="w-50 text-center">Idcategoriaprov</th>
      <th class="w-50 text-center">Comentario</th>
    </tr>
  </thead>

  <tbody>
    <% @proveedores.each do |proveedore| %>
      <tr>
        <td><%= proveedore.identificacion %></td>
        <td><%= proveedore.nombre %></td>
        <td><%= proveedore.idCiudad %></td>
        <td><%= proveedore.idDpto %></td>
        <td><%= proveedore.dirreccion %></td>
        <td><%= proveedore.correo %></td>
        <td><%= proveedore.telefonos %></td>
        <td><%= proveedore.idTipoProv %></td>
        <td><%= proveedore.idEstadoProv %></td>
        <td><%= proveedore.idCategoriaProv %></td>
        <td><%= proveedore.comentario %></td>
        <!--<td><%= link_to 'Show', proveedore %></td>
        <td><%= link_to 'Edit', edit_proveedore_path(proveedore) %></td>
        <td><%= link_to 'Destroy', proveedore, method: :delete, data: { confirm: 'Are you sure?' } %>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/proveedores/new.html.erb
<h1>Nuevo Proveedor</h1>

<%= link_to 'Regresar', proveedores_path, class:"btn btn-info" %>

<%= render 'form', proveedore: @proveedore %>

app/views/proveedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identificacion:</strong>
  <%= @proveedore.identificacion %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @proveedore.nombre %>
</p>

<p>
  <strong>Idciudad:</strong>
  <%= @proveedore.idCiudad %>
</p>

<p>
  <strong>Iddpto:</strong>
  <%= @proveedore.idDpto %>
</p>

<p>
  <strong>Dirreccion:</strong>
  <%= @proveedore.dirreccion %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @proveedore.correo %>
</p>

<p>
  <strong>Telefonos:</strong>
  <%= @proveedore.telefonos %>
</p>

<p>
  <strong>Idtipoprov:</strong>
  <%= @proveedore.idTipoProv %>
</p>

<p>
  <strong>Idestadoprov:</strong>
  <%= @proveedore.idEstadoProv %>
</p>

<p>
  <strong>Idcategoriaprov:</strong>
  <%= @proveedore.idCategoriaProv %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @proveedore.comentario %>
</p>

<%= link_to 'Edit', edit_proveedore_path(@proveedore) %> |
<%= link_to 'Back', proveedores_path %>