config/routes.rb
Rails.application.routes.draw do

  resources :asignaciones
  resources :proveedores
  resources :personas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/login', to:'seguridad#login'
  get '/inicio', to:'inicio#casa'
  get '/noacceso', to:'inicio#noacceso'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignacione.rb
class Asignacione < ApplicationRecord
  belongs_to :persona
end

app/models/equipo.rb
# == Schema Information
#
# Table name: equipos
#
#  id             :integer          not null, primary key
#  Placa          :string
#  Modelo         :string
#  Serie          :string
#  IdEstadoEquipo :string
#  IdTipoEquipo   :string
#  IdArea         :string
#  eliminado      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Equipo < ApplicationRecord
	has_many :vencimientos
end

app/models/opcione.rb
# == Schema Information
#
# Table name: opciones
#
#  id           :integer          not null, primary key
#  idpadre      :integer
#  opcion       :string
#  url          :string
#  estadoopcion :string
#  orden        :string
#  eshoja       :boolean
#  controller   :string
#  eliminado    :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Opcione < ApplicationRecord
	has_many :rol_opcion_operacione
end

app/models/parametro.rb
# == Schema Information
#
# Table name: parametros
#
#  id              :integer          not null, primary key
#  atributo        :string
#  descripcion     :string
#  estadoParametro :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Parametro < ApplicationRecord
	has_many :valor_parametro
	
end

app/models/persona.rb
class Persona < ApplicationRecord
	has_many :asignaciones
end

app/models/proveedore.rb
class Proveedore < ApplicationRecord
end

app/models/usuario.rb
# == Schema Information
#
# Table name: usuarios
#
#  id              :integer          not null, primary key
#  usuario         :string
#  idrol           :integer
#  idestadousuario :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  eliminado       :integer          default(0)
#  password        :string
#

include Servicios
class Usuario < ApplicationRecord  
	 before_save :encriptarPass
	
   has_many :rol_opcion_operacione
      
  validates :usuario, presence: true, length: { minimum: 4 },
    uniqueness: { case_sensitive: false,message: "Usuario existe. Verifique" }
  validates :password, presence: {message: "Debe agregar un password valido." }

  scope :sin_eliminados, -> { where(eliminado: 0)   }

  private 
  def encriptarPass 
    if self.password !=nil           	
    	self.password = Encriptar(self.password)
    end    
 end

end

app/models/valor_parametro.rb
# == Schema Information
#
# Table name: valor_parametros
#
#  id                   :integer          not null, primary key
#  parametroId          :integer
#  valor                :string
#  orden                :string(3)
#  estadoValorParametro :string(1)
#  eliminado            :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  parametro_id         :integer
#

class ValorParametro < ApplicationRecord
	 belongs_to :parametro
end

app/models/vencimiento.rb
# == Schema Information
#
# Table name: vencimientos
#
#  id                  :integer          not null, primary key
#  Equipo_id           :integer
#  FechaInicion        :date
#  FechaFinal          :date
#  Comentario          :string
#  IdTipoVencimineto   :string
#  IdEstadoVencimiento :string
#  Referencia          :string
#  eliminado           :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Vencimiento < ApplicationRecord
  belongs_to :Equipo
end

app/controllers/asignaciones_controller.rb
class AsignacionesController < BaseController
  before_action :set_asignacione, only: [:show, :edit, :update, :destroy]

  # GET /asignaciones
  # GET /asignaciones.json
  def index
    @asignaciones = Asignacione.all
  end

  # GET /asignaciones/1
  # GET /asignaciones/1.json
  def show
  end

  # GET /asignaciones/new
  def new
    @asignacione = Asignacione.new
  end

  # GET /asignaciones/1/edit
  def edit
  end

  # POST /asignaciones
  # POST /asignaciones.json
  def create
    @asignacione = Asignacione.new(asignacione_params)

    respond_to do |format|
      if @asignacione.save
        format.html { redirect_to @asignacione, notice: 'Asignacione was successfully created.' }
        format.json { render :show, status: :created, location: @asignacione }
      else
        format.html { render :new }
        format.json { render json: @asignacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaciones/1
  # PATCH/PUT /asignaciones/1.json
  def update
    respond_to do |format|
      if @asignacione.update(asignacione_params)
        format.html { redirect_to @asignacione, notice: 'Asignacione was successfully updated.' }
        format.json { render :show, status: :ok, location: @asignacione }
      else
        format.html { render :edit }
        format.json { render json: @asignacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaciones/1
  # DELETE /asignaciones/1.json
  def destroy
    @asignacione.destroy
    respond_to do |format|
      format.html { redirect_to asignaciones_url, notice: 'Asignacione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignacione
      @asignacione = Asignacione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignacione_params
      params.require(:asignacione).permit(:persona_id, :fecha, :idEstadoPersonaEquipo, :eliminado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaciones_helper.rb
module AsignacionesHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/opciones_helper.rb
module OpcionesHelper
end

app/helpers/parametros_helper.rb
module ParametrosHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/helpers/seguridad_helper.rb
module SeguridadHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/asignaciones/_form.html.erb
<%= form_with(model: asignacione, local: true) do |form| %>
  <% if asignacione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asignacione.errors.count, "error") %> prohibited this asignacione from being saved:</h2>

      <ul>
      <% asignacione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row col-sm-4">
    <%= form.label :persona_id %>
    <%= form.text_field :persona_id, id: :asignacione_persona_id, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :asignacione_fecha, class:"form-control"  %>
  </div>

  <div class="form-group row col-sm-4 "> 
    <%= form.label :idEstadoPersonaEquipo %>
    <%= form.number_field :idEstadoPersonaEquipo, id: :asignacione_idEstadoPersonaEquipo, class:"form-control" %>
  </div>
<!--
  <div class="form-group row col-sm-4">
    <%= form.label :eliminado %>
    <%= form.number_field :eliminado, id: :asignacione_eliminado, class:"form-control" %>
  </div>
-->
  <div class="actions">
    <%= form.submit "Guardar", :class=>"btn btn-secondary"%>
    <%= link_to 'Eliminar', asignacione, :class => "btn btn-danger", method: :delete, data: { confirm: 'Confirme Eliminación?' } %></td>
  </div>
<% end %>

app/views/asignaciones/edit.html.erb
<h1>Editing Asignacione</h1>

<%= render 'form', asignacione: @asignacione %>

<%= link_to 'Show', @asignacione %> |
<%= link_to 'Back', asignaciones_path %>

app/views/asignaciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asignaciones</h1>

<%= link_to 'Nuevo', new_asignacione_path,class:'btn btn-primary btn-sm' %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="w-50 text-center">Persona</th>
      <th class="w-50 text-center">Fecha</th>
      <th class="w-50 text-center">Idestadopersonaequipo</th>
      <!-- <th class="w-50 text-center">Eliminado</th> -->
    
    </tr>
  </thead>

  <tbody>
    <% @asignaciones.each do |asignacione| %>
      <tr>
        <td><%= asignacione.persona %></td>
        <td><%= asignacione.fecha %></td>
        <td><%= asignacione.idEstadoPersonaEquipo %></td>
       <!-- <td><%= asignacione.eliminado %></td>
        <td><%= link_to 'Show', asignacione %></td>
        <td><%= link_to 'Edit', edit_asignacione_path(asignacione) %></td>
        <td><%= link_to 'Destroy', asignacione, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/asignaciones/new.html.erb
<h1>Nueva Asignación</h1>

<%= link_to 'Regresar', asignaciones_path, class:"btn btn-info" %>

<%= render 'form', asignacione: @asignacione %>

app/views/asignaciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Persona:</strong>
  <%= @asignacione.persona %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @asignacione.fecha %>
</p>

<p>
  <strong>Idestadopersonaequipo:</strong>
  <%= @asignacione.idEstadoPersonaEquipo %>
</p>
<!--
<p>
  <strong>Eliminado:</strong>
  <%= @asignacione.eliminado %>
</p>
-->

<%= link_to 'Edit', edit_asignacione_path(@asignacione) %> |
<%= link_to 'Back', asignaciones_path %>