config/routes.rb
Rails.application.routes.draw do

  resources :asignaciones
  resources :proveedores
  resources :personas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/login', to:'seguridad#login'
  get '/inicio', to:'inicio#casa'
  get '/noacceso', to:'inicio#noacceso'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rol_opcion_operacione.rb
# == Schema Information
#
# Table name: rol_opcion_operaciones
#
#  id          :integer          not null, primary key
#  idrol       :integer
#  idoperacion :integer
#  eliminado   :integer          default(0)
#  estadorolop :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  opcione_id  :integer
#  usuario_id  :integer
#

class RolOpcionOperacione < ApplicationRecord
	belongs_to :opcione	
end

app/controllers/rol_opcion_operaciones_controller.rb
class RolOpcionOperacionesController <  BaseController
  before_action :set_rol_opcion_operacione, only: [:show, :edit, :update, :destroy]

  include Servicios
  # GET /rol_opcion_operaciones
  # GET /rol_opcion_operaciones.json
  def index
    @todos = RolOpcionOperacione.all.order('idrol,Opcione_id,idoperacion')
     @regs = @todos.map do |r|
       {
         "id"            => r.id,
         "rol"           => TraerValorParametro(r.idrol),
         "opcion"        => TraerOpcion(r.opcione_id),    
         "idopcion"      => r.opcione_id,          
         "operacion"     => TraerValorParametro(r.idoperacion),
         "estado"        => r.estadorolop
        }
      end
      
  end

  # GET /rol_opcion_operaciones/1
  # GET /rol_opcion_operaciones/1.json
  def show

     @reg = {
         "id"            => @rol_opcion_operacione.id,
         "rol"           => TraerValorParametro(@rol_opcion_operacione.idrol),
         "opcion"        => TraerOpcion(@rol_opcion_operacione.opcione_id),              
         "operacion"     => TraerValorParametro(@rol_opcion_operacione.idoperacion),
         "estado"        => @rol_opcion_operacione.estadorolop
        }

        pp "reg=",@reg
       
  end
  # GET /rol_opcion_operaciones/new
  def new
    @rol_opcion_operacione = RolOpcionOperacione.new
    set_variables_g

  end

  # GET /rol_opcion_operaciones/1/edit
  def edit
    set_variables_g
  end

  # POST /rol_opcion_operaciones
  # POST /rol_opcion_operaciones.json
  def create
    @rol_opcion_operacione = RolOpcionOperacione.new(rol_opcion_operacione_params)

    respond_to do |format|
      if @rol_opcion_operacione.save
        format.html { redirect_to @rol_opcion_operacione, notice: 'Acceso creado eitosamente' }
        format.json { render :show, status: :created, location: @rol_opcion_operacione }
      else
        format.html { render :new }
        format.json { render json: @rol_opcion_operacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rol_opcion_operaciones/1
  # PATCH/PUT /rol_opcion_operaciones/1.json
  def update
    respond_to do |format|
      if @rol_opcion_operacione.update(rol_opcion_operacione_params)
        format.html { redirect_to @rol_opcion_operacione, notice: 'Acceso actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @rol_opcion_operacione }
      else
        format.html { render :edit }
        format.json { render json: @rol_opcion_operacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rol_opcion_operaciones/1
  # DELETE /rol_opcion_operaciones/1.json
  def destroy
    @rol_opcion_operacione.destroy
    respond_to do |format|
      format.html { redirect_to rol_opcion_operaciones_url, notice: 'Acceso borrado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def set_variables_g
     @roles = TraerParametros(2)
     @operaciones=TraerParametros(3)     
     @opciones=Opcione.select("id,opcion").where("estadoopcion='A'")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol_opcion_operacione
      @rol_opcion_operacione = RolOpcionOperacione.find(params[:id])
     end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_opcion_operacione_params
      params.require(:rol_opcion_operacione).permit(:usuario_id, :opcione_id, :idrol, :idoperacion, :eliminado, :estadorolop)
    end
end

app/helpers/rol_opcion_operaciones_helper.rb
module RolOpcionOperacionesHelper
end

app/views/rol_opcion_operaciones/_form.html.erb
<div class="container mt-3">
  <%= form_with(model: rol_opcion_operacione, local: true) do |form| %>
    <% if rol_opcion_operacione.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(rol_opcion_operacione.errors.count, "error") %> prohibited this rol_opcion_operacione from being saved:</h2>

        <ul>
        <% rol_opcion_operacione.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="form-group row col-sm-4">
      
      <%= form.label :"Rol:" %>
      <% opciones = options_from_collection_for_select(@roles, "id","valor",rol_opcion_operacione.idrol) %>
      <%= form.select(:idrol, opciones,{},{class:"form-control"} ) %>  
      
    </div>
  <div class="form-group row col-sm-4">
      <%= form.label "Opcion:" %>
      <% opciones = options_from_collection_for_select(@opciones, "id","opcion",rol_opcion_operacione.opcione_id) %>
      <%= form.select(:opcione_id, opciones,{},{class:"form-control"} ) %> 
    </div>
    <div class="form-group row col-sm-4">
      <%= form.label "Operación:" %>
      <% opciones = options_from_collection_for_select(@operaciones, "id","valor",rol_opcion_operacione.idoperacion) %>
      <%= form.select(:idoperacion, opciones,{},{class:"form-control"} ) %> 
     
    </div>

    <div class="form-group row col-sm-4">
      <%= form.label "Estado:" %>
      <%= form.text_field :estadorolop, id: :rol_opcion_operacione_estadorolop, class:"form-control" %>
    </div>

    <div class="actions">
      <%= form.submit  "Guardar", :class=>"btn btn-secondary" %>
      <%= link_to 'Eliminar', rol_opcion_operacione, :class => "btn btn-danger", method: :delete, data: { confirm: 'Confirme Eliminación?' } %>
    </div>
  <% end %>
</div>

app/views/rol_opcion_operaciones/edit.html.erb
<h4>Modificar Accesos</h4>
<hr class="division">
<%= link_to 'Regresar', rol_opcion_operaciones_path,class:"btn btn-info" %>
<%= render 'form', rol_opcion_operacione: @rol_opcion_operacione %>

app/views/rol_opcion_operaciones/index.html.erb
<h4>Lista de Accesos</h4>
<hr class="division">
<%= link_to 'Nuevo', new_rol_opcion_operacione_path,class:'btn btn-primary btn-sm' %>
<p id="notice"><%= notice %></p>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Rol</th>         
      <th>Opción</th> 
      <th>idOpción</th> 
      <th>Operacion</th>    
      <th>Estado</th>      
    </tr>
  </thead>

  <tbody>
    <% @regs.each do |reg| %>
      <tr>
        <td><a class="llaves" href="/rol_opcion_operaciones/<%= reg['id'] %>"> <%= reg['id'] %></a>    
        <td><%= reg['rol']       %></td>
        <td><%= reg['opcion']    %></td>
        <td><%= reg['idopcion']  %></td>
        <td><%= reg['operacion'] %></td>       
        <td><%= reg['estado']    %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rol_opcion_operaciones/new.html.erb
<h4>Nuevo Acceso</h4>
<hr class="division">
<%= link_to 'Regresar',rol_opcion_operaciones_path, class:"btn btn-info" %>

<%= render 'form', rol_opcion_operacione: @rol_opcion_operacione %>

app/views/rol_opcion_operaciones/show.html.erb
<h4>Información de Acceso</h4>
<hr class="division">
<%= link_to 'Regresar', rol_opcion_operaciones_path,class:"btn btn-info" %>

<p id="notice"><%= notice %></p>
<form >

	<div class="form-group col-md-4">
	  <label>Rol:</label>
	  <input type="text" class="form-control" value="<%= @reg['rol'] %>" readonly >
	</div>
    <div class="form-group col-md-4">
	  <label>Opcion:</label>
	  <input type="text" class="form-control" value="<%= @reg['opcion']  %>" readonly >
	</div>
	<div class="form-group col-md-4">
	  <label>Operación:</label>
	  <input type="text" class="form-control" value="<%= @reg['operacion']  %>" readonly >
	</div>

	<div class="form-group col-md-4">
	  <label>Estado:</label>
	 <input type="text" class="form-control" value="<%= @reg['estado']  %>" readonly >
	</div>
</form>

<%= link_to 'Modificar', edit_rol_opcion_operacione_path(@rol_opcion_operacione),class:"btn btn-success" %> 